# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY  # Using Cloud Logging only

# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud builds submit --tag gcr.io/$PROJECT_ID/$REPO_NAME
    gcloud run deploy $REPO_NAME \
      --image gcr.io/$PROJECT_ID/$REPO_NAME \
      --platform managed \
      --region us-central1 \
      --allow-unauthenticated

timeout: '10m'
