# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY  # Or logging: NONE 

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/node'  # Use the 'node' image
  args: ['server.js']  # Directly run server.js
timeout: '1600s'