# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY  # Using Cloud Logging only

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/node:18'  
  args: ['server.js']
logsBucket: 'gs://wedding-rsvp-build-logs'  # Replace with your actual bucket name
timeout: '1600s'
