# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY  # Using Cloud Logging only

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'node:18'  # Using the official Node.js image from Docker Hub
  entrypoint: 'node'
  args: ['server.js']
timeout: '1600s'